services:
  db:
    image: postgres:16
    container_name: petshop-db
    environment:
      POSTGRES_DB: petshop
      POSTGRES_USER: petshop
      POSTGRES_PASSWORD: petshop
    ports:
      - "5433:5432"
    volumes:
      - petshop_pg:/var/lib/postgresql/data
volumes:
  petshop_pg: